# Site wide configuration

title: int13
description: "A place for knowledge, software craftsmanship, performance and stability."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: https://ewirch.github.io
analytics: true

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:year/:month/:title.html
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed


# Site owner
owner:
  name: Eduard Wirch
  web: https://ewirch.github.io/
  email: wirch.eduard@gmail.com
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +EduardWirch
  disqus-shortname: ewirch


include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - readme.txt
