# Site wide configuration

title: int13
description: "A place for knowledge, software craftsmanship, performance and stability."
locale: "en-US"
url: https://ewirch.github.io
github_username: ewirch
repository: "ewirch/ewirch.github.io"
minimal_mistakes_skin: default
search: true


# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.18.1"
# Outputting
permalink: /:year/:month/:title.html
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Berlin

# Jekyll configuration

include:
  - _pages

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# Site owner
author:
  name: Eduard Wirch
  avatar: "/assets/images/bio-photo.jpg"
  location: "Berlin, Germany"
  #  bio    : "My awesome biography constrained to a sentence or two goes here."
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wirch.eduard@gmail.com"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ewirch"
    - label: Stack Overflow
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/17428/eduard-wirch"
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eduard-wirch-a87099157/"
footer:
  links:
    - label: Email
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wirch.eduard@gmail.com"
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ewirch"
    - label: Stack Overflow
      icon: "fab fa-fw fa-stack-overflow"
      url: "https://stackoverflow.com/users/17428/eduard-wirch"
    - label: Linkedin
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/eduard-wirch-a87099157/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "disqus"
  disqus:
    shortname: "ewirch"

nalytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-61571226-1"
    anonymize_ip: false # default

