# Site wide configuration

title: int13
description: "A place for knowledge, software craftsmanship, performance and stability."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: https://ewirch.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
#permalink: /:categories/:title/
permalink: /:year/:month/:title.html
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap

  
# Site owner
owner:
  name: Eduard Wirch
  web: https://ewirch.github.io/
  email: wirch.eduard@gmail.com
#  bio: ""
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: +EduardWirch
  disqus-shortname: ewirch


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
